#!/bin/bash
#stop tomcat {{{1
source /etc/profile
source ~/.bash_profile
if [[ -z $2 ]] || [[ -z $1 ]]; then
	echo -e "Please Input Parameter(\033[44;31;1meg.command 3 btm \033[0m)";exit 2
fi

cd "/web/service/"
target=`ls | awk /$2/`
if [[ $2 =~ ^[0-9]{4}$ ]];then echo -e "\033[1;33;1m$target\033[0m";else echo -e "is this tomcat port? \033[1;31;1m$2\033[0m" ; exit 2;fi
if [[ ! -d $target ]] ;then echo "No this tomcat exit............" ;exit 2;fi
flag=`netstat -ntlp | awk /$2/`
cd $target
if [ "$1" == "1" ]
        then if [[ -z $flag ]]; then echo "Is tomcat Stoped!" ;exit;else bin/shutdown.sh && rm -rf logs/* && rm -rf log/*  && echo "logs rm ok";bin/startup.sh ;fi;
fi
if [ "$1" == "2" ]
        #then if [[ ! -z $flag ]]; then echo "Is tomcat Running!" ;exit 2;else rm -rf logs/* && echo "logs rm ok!"; bin/startup.sh && tail -f logs/catalina.out;fi;
        then if [[ ! -z $flag ]]; then echo "Is tomcat Running!" ;exit 2;else rm -rf log/* && rm -rf logs/* && echo "logs rm ok!"; bin/startup.sh ;fi;
fi
if [ "$1" == "3" ]
        then if [[ -z $flag ]]; then echo "Is tomcat Stoped!" ;exit 2;else bin/shutdown.sh ;fi;
fi
if [ "$1" == "7" ]
        then if [[ -z $flag ]]; then echo "Is tomcat Stoped!" ;exit 2;else tail -f logs/catalina.out ;fi;
fi
##假装我是动感超人，完成全部的判断了{{{2
#echo $1"shutdown down!"
#
##cp app code to tmpdir{{{1
#mkdir /tmp/deploytmp
#wget $url
#jar xvf btm.war
#cp override/btm /web/eln4share/test2/btm
#rm -rf /tmp/deploytmp
##假装我是动感超人，cp done!{{{2
#
#echo $1"cp down!"
#
##startup tomcat{{{1
##假装我是动感超人，ok{{{2
#
#
#echo $1"SUCCESSFUL!"
