#!/bin/bash
#stop tomcat {{{1
if [[ $1 == "help" ]];then #{{{
	echo -e "\033[32;1m--------------------------------------------------------\033[0m"
	awk 'BEGIN{
		printf "%-8s%-15s%-15s\n"," Usage: ","      $1       ","      $2       "
		printf "%-8s%-15s%-15s\n","        ","     _______   ","     _______   "
		printf "%-8s%-15s%-15s\n","        ","    |appcode|  ","    |Action |  "
		printf "%-8s%-15s%-15s\n","        ","               ","               "
		printf "%-8s%-15s%-15s\n","        ","               ","  ____________ "
		printf "%-8s%-15s%-15s\n","        "," _____________ "," |start/2     |"
		printf "%-8s%-15s%-15s\n","        ","|uc-web,uc-svc|"," |restart/1   |"
		printf "%-8s%-15s%-15s\n","        ","               "," |shutdown/3  |"
		printf "%-8s%-15s%-15s\n","        ","               "," |logcheck/4  |"
		printf "%-8s%-15s%-15s\n","        ","               "," |logtrack/7  |"
		printf "%-8s%-15s%-15s\n","        ","               "," |autodeploy/6|"
		printf "%-8s%-15s%-15s\n","        ","               ","               "
		}'
fi
if [[ -z $1 ]] || [[ -z $2 ]] 
then
	echo -e "\033[33;1mVariable is null please check \033[0m" && exit 2
elif [[ "$1" =~ ^[a-z0-9]{2,}-(web|svc),([a-z0-9]{2,}-(web|svc),)*([a-z0-9]{2,}-(web|svc))$ ]]
then
	len=$((`echo $1 | grep -o "," | wc -l`+1))
	for ((i=1;i<=$len;i++))
	do
		echo -e "##############################deploy \033[33;1m"`echo $1 | awk -v t=$i 'BEGIN{FS=","};END{printf$t}'`"\033[0m##############################\n"
		/web/eln4share/test/new/zlfcommandload `echo $1 | awk -v t=$i 'BEGIN{FS=","};END{printf$t}'` 3 $2 $3 
		sleep 1
	done
elif [[ "$1" =~ ^[a-z]{2,}-(web|svc) ]]
then
	/web/eln4share/test/new/zlfcommandload $1 3 $2 $3 $4
else
	echo -e "Variable is don't match \033[33;1maf-web,tt-svc,server-web\033[0m or \033[33;1mapp-(web|svc)\033[0m please check " && exit 2
fi



##假装我是动感超人，完成判断了{{{2
#echo $1"shutdown down!"
#
##cp app code to tmpdir{{{1
#mkdir /tmp/deploytmp
#wget $url
#jar xvf btm.war
#cp override/btm /web/eln4share/test2/btm
#rm -rf /tmp/deploytmp
##假装我是动感超人，cp done!{{{2
#
#echo $1"cp down!"
#
##startup tomcat{{{1
##假装我是动感超人，ok{{{2
#
#
#echo $1"SUCCESSFUL"
