#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/web/nagios/libexec/
LANG=zh_CN.UTF-8
export LANG
export PATH
#just judge home or shanghai{{{1
WEATHER_URL='http://www.weather.com.cn/weather/101020100.shtml'
city="SH"

TMP_FILE='weather_html'
cd /tmp
wget -t 3 -w 59 -T 59 $WEATHER_URL -O ${TMP_FILE} >/dev/null 2>&1 
dos2unix ${TMP_FILE} >/dev/null 2>&1 
cat weather_html | sed -e :a -e 's/<[^>]*>//g;/</N;//ba' | sed '/^[[:space:]]*$/d' | sed 's/[[:space:]]//g' | sed '/^[a-Z]/d' | sed '/[{/}/;]/d' | grep "查看未来4-7天天气预报" -A 78 > temp.t
echo $city > message
for ((i=0;i<7;i++))
do
	t=`date -d "+$i day" "+%w"`
	if (( $t == 1 )) ; then t=星期一;elif (( $t == 2 ));then t=星期二;elif (( $t == 3 ));then t=星期三;elif (( $t == 4 ));then t=星期四;elif (( $t == 5 ));then t=星期五;elif (( $t == 6 ));then t=星期六;elif (( $t == 0 ));then t=星期日;fi
	day[$i]=`date --date="+$i day" "+%-d"日``echo $t`
	if [ $i == 0 ]
	then
	cat temp.t | grep "${day[$i]}" -A 10 | awk 'BEGIN{ORS=" "}1' | awk '{if ($7!="夜间"){printf("%s 白天%s%s的%s,%s\n",$1,$3,$6,$5,$4)} else {printf("%s 白天%s%s的%s,夜间%s%s的%s,%s-%s\n",$1,$3,$6,$5,$8,$11,$10,$9,$4)}}' >> message
	elif [ $i == 6 ] 
	then
	cat temp.t | grep "${day[$i]}" -A 10 | awk 'BEGIN{ORS=" "}1' | awk '{if ($7==""){printf("%s 白天%s%s的%s,%s\n",$1,$3,$6,$5,$4)} else {printf("%s 白天%s%s的%s,夜间%s%s的%s,%s-%s\n",$1,$3,$6,$5,$8,$11,$10,$9,$4)}}' >> message
	else
	cat temp.t | grep "${day[$i]}" -A 10 | awk 'BEGIN{ORS=" "}1' | awk '{printf("%s 白天%s%s的%s,夜间%s%s的%s,%s-%s\n",$1,$3,$6,$5,$8,$11,$10,$9,$4)}' >> message
	fi	
done
#/web/nagios/libexec/fetion --mobile=15221556659 --pwd=1qazxsw2 --to=15221556659 --msg-type=1 --file-utf8=/tmp/message
cat /tmp/message
rm -rf ${TMP_FILE}
rm temp.t message
